### ISSUE TITLE
Cannot find module '../lib/sub_command

### ISSUE THREAD

**Issue by VladimirAlexiev** [maxlath/wikibase-cli#94]
```
> wd f google -v
{ Error: Cannot find module '../lib/sub_command'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at lightGet.then.body (C:\Users\vladimir.alexiev.000\AppData\Roaming\npm\node_modules\wikibase-cli\bin\wb-search:73:5)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) code: 'MODULE_NOT_FOUND' }
```

Note: `wd f google` without `-f` works fine.

**Comment by maxlath** [comment]
this should have been fixed by 0eae317 and thus be working in versions `>= v8.1.1`

**Comment by VladimirAlexiev** [comment]
works in `wikibase-cli@8.2.0`
